import {
  badge,
  bank,
  briefcase,
  chartBar,
  clipboard,
  coins,
  friends,
  galaxy,
  handShake,
  loan,
  piggy,
  sack,
  scroll,
  sliders,
  transaction,
  userCheck,
  userCog,
  users,
  userX,
} from "@/public/icons";

export const sideBarContent = {
  customers: [
    { text: "users", icon: friends, href: "#" },
    { text: "guarantors", icon: users, href: "#" },
    { text: "loans", icon: sack, href: "#" },
    { text: "decison models", icon: handShake, href: "#" },
    { text: "savings", icon: piggy, href: "#" },
    { text: "loan request", icon: loan, href: "#" },
    { text: "whitelist", icon: userCheck, href: "#" },
    { text: "karma", icon: userX, href: "#" },
  ],
  businesses: [
    { text: "organization", icon: briefcase, href: "#" },
    { text: "loan products", icon: loan, href: "#" },
    { text: "savings products", icon: bank, href: "#" },
    { text: "fees and charges", icon: coins, href: "#" },
    { text: "transactions", icon: transaction, href: "#" },
    { text: "services", icon: galaxy, href: "#" },
    { text: "service account", icon: userCog, href: "#" },
    { text: "settlements", icon: scroll, href: "#" },
    { text: "reports", icon: chartBar, href: "#" },
  ],
  settings: [
    { text: "preferences", icon: sliders, href: "#" },
    { text: "fees and pricing", icon: badge, href: "#" },
    { text: "audit logs", icon: clipboard, href: "#" },
  ],
};
