import {
  badge,
  bank,
  briefcase,
  chartBar,
  clipboard,
  coins,
  friends,
  galaxy,
  handShake,
  loan,
  piggy,
  sack,
  scroll,
  sliders,
  transaction,
  userCheck,
  userCog,
  users,
  userX,
} from "@/public/icons";
import { friends2 } from "@/public/images";

export const sideBarContent = {
  customers: [
    { text: "users", icon: friends, href: "/users" },
    { text: "guarantors", icon: users, href: "#" },
    { text: "loans", icon: sack, href: "#" },
    { text: "decison models", icon: handShake, href: "#" },
    { text: "savings", icon: piggy, href: "#" },
    { text: "loan request", icon: loan, href: "#" },
    { text: "whitelist", icon: userCheck, href: "#" },
    { text: "karma", icon: userX, href: "#" },
  ],
  businesses: [
    { text: "organization", icon: briefcase, href: "#" },
    { text: "loan products", icon: loan, href: "#" },
    { text: "savings products", icon: bank, href: "#" },
    { text: "fees and charges", icon: coins, href: "#" },
    { text: "transactions", icon: transaction, href: "#" },
    { text: "services", icon: galaxy, href: "#" },
    { text: "service account", icon: userCog, href: "#" },
    { text: "settlements", icon: scroll, href: "#" },
    { text: "reports", icon: chartBar, href: "#" },
  ],
  settings: [
    { text: "preferences", icon: sliders, href: "#" },
    { text: "fees and pricing", icon: badge, href: "#" },
    { text: "audit logs", icon: clipboard, href: "#" },
  ],
};

export const tableHeader: string[] = [
  "organization",
  "username",
  "email",
  "phone number",
  "date joined",
  "status",
  "",
];

export const userAnalytics: userAnalyticsType[] = [
  { title: "users", icon: "/images/friends2-group.png", value: 489383 },
  { title: "active users", icon: "/images/b-users-group.png", value: 38929 },
  {
    title: "users with loans",
    icon: "/images/ledger-group.png",
    value: 7227,
  },
  {
    title: "users with savings",
    icon: "/images/stacked-coins-group.png",
    value: 38392,
  },
];

export const usersMock: userListData[] = [
  {
    organization: "lendsqr",
    userName: "Adedeji",
    email: "adedeji@lendsqr.com",
    phoneNumber: "080789987645",
    dateJoined: "may 15, 2020 10:00 AM",
    status: "inactive",
    id: "2i22je8j2",
  },
  {
    organization: "irorun",
    userName: "salako",
    email: "salako@irorun.com",
    phoneNumber: "09027287645",
    dateJoined: "june 22, 2025 12:22 PM",
    status: "blacklisted",
    id: "338wj33",
  },
  {
    organization: "lendstar",
    userName: "matthew cussons",
    email: "matthew@lendstar.com",
    phoneNumber: "0071273627383",
    dateJoined: "sept 07, 2007 18:37 PM",
    status: "pending",
    id: "3jwi2io2",
  },
  {
    organization: "lendsqr",
    userName: "badmus denrele",
    email: "badmus@lendsqr.com",
    phoneNumber: "7928191910",
    dateJoined: "july 27, 2011 09:44 AM",
    status: "active",
    id: "3u3jenop",
  },
  {
    organization: "lendsqr",
    userName: "simmons",
    email: "simmons@lendsqr.com",
    phoneNumber: "82928292922",
    dateJoined: "oct 23, 2015 14:00 PM",
    status: "inactive",
    id: "383iew3",
  },
  {
    organization: "lendstar",
    userName: "carl jenson",
    email: "carl@lendstar.com",
    phoneNumber: "384937392822",
    dateJoined: "dec 31, 2017 15:17 PM",
    status: "pending",
    id: "383jw922",
  },
  {
    organization: "irorun",
    userName: "denver utah",
    email: "denver@irorun.com",
    phoneNumber: "080789987645",
    dateJoined: "may 15, 2020 10:00 AM",
    status: "blacklisted",
    id: "3k0wwm2",
  },
  {
    organization: "irorun",
    userName: "Adedeji",
    email: "adedej2wi@lendsqr.com",
    phoneNumber: "080789987645",
    dateJoined: "may 15, 2020 10:00 AM",
    status: "active",
    id: "i2w22m",
  },
  {
    organization: "lendstar",
    userName: "Adedeji",
    email: "adedeji22@lendsqr.com",
    phoneNumber: "080789987645",
    dateJoined: "may 15, 2020 10:00 AM",
    status: "inactive",
    id: "j2mwwom2",
  },
  {
    organization: "lendsqr",
    userName: "Adedeji",
    email: "adedeji1@lendsqr.com",
    phoneNumber: "080789987645",
    dateJoined: "may 15, 2020 10:00 AM",
    status: "active",
    id: "9222n2",
  },
];
